export enum AUTHORIZER_EVENTS {
  CREATE_USER = 'CREATE_USER',
  SEND_VERIFICATION_CODE = 'SEND_VERIFICATION_CODE',
  VERIFY_USER = 'VERIFY_USER',
  LOGIN = 'LOGIN',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
}
